const fs = require("fs")
const path = require("path")

function write(file, content) {
  if (!fs.existsSync(file)) {
    fs.writeFileSync(file, content.trim() + "\n")
  }
}

async function run(projectDir, options) {

  const projectName = options.name
  const framework = options.framework

  /* -------------------------
  README
  ------------------------- */

  write(
    path.join(projectDir, "README.md"),
`# ${projectName}

Built with **create-bawo-frontend**.

## Tech Stack

- ${framework}
- Vite
- TailwindCSS

## Install

\`\`\`bash
npm install
\`\`\`

## Start Development

\`\`\`bash
npm run dev
\`\`\`

## Build

\`\`\`bash
npm run build
\`\`\`

## Preview

\`\`\`bash
npm run preview
\`\`\`

---

Generated by **create-bawo-frontend**
https://create-bawo-frontend.vercel.app/docs
`
  )

  /* -------------------------
  EditorConfig
  ------------------------- */

  write(
    path.join(projectDir, ".editorconfig"),
`root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
`
  )

  /* -------------------------
  Prettier
  ------------------------- */

  write(
    path.join(projectDir, ".prettierrc"),
`{
  "singleQuote": true,
  "semi": false,
  "printWidth": 80
}`
  )

}

module.exports = { run }