module.exports = {
  inter: { family: "Inter", url: "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" },
  poppins: { family: "Poppins", url: "https://fonts.googleapis.com/css2?family=Poppins:wght@100..900&display=swap" },
  roboto: { family: "Roboto", url: "https://fonts.googleapis.com/css2?family=Roboto:wght@100..900&display=swap" },
  openSans: { family: "Open Sans", url: "https://fonts.googleapis.com/css2?family=Open+Sans:wght@100..900&display=swap" },
  lato: { family: "Lato", url: "https://fonts.googleapis.com/css2?family=Lato:wght@100..900&display=swap" },
  montserrat: { family: "Montserrat", url: "https://fonts.googleapis.com/css2?family=Montserrat:wght@100..900&display=swap" },
  nunito: { family: "Nunito", url: "https://fonts.googleapis.com/css2?family=Nunito:wght@100..900&display=swap" },
  raleway: { family: "Raleway", url: "https://fonts.googleapis.com/css2?family=Raleway:wght@100..900&display=swap" },
  ubuntu: { family: "Ubuntu", url: "https://fonts.googleapis.com/css2?family=Ubuntu:wght@100..900&display=swap" },
  rubik: { family: "Rubik", url: "https://fonts.googleapis.com/css2?family=Rubik:wght@100..900&display=swap" },

  dmSans: { family: "DM Sans", url: "https://fonts.googleapis.com/css2?family=DM+Sans:wght@100..900&display=swap" },
  workSans: { family: "Work Sans", url: "https://fonts.googleapis.com/css2?family=Work+Sans:wght@100..900&display=swap" },
  sourceSans3: { family: "Source Sans 3", url: "https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@100..900&display=swap" },
  manrope: { family: "Manrope", url: "https://fonts.googleapis.com/css2?family=Manrope:wght@100..900&display=swap" },
  archivo: { family: "Archivo", url: "https://fonts.googleapis.com/css2?family=Archivo:wght@100..900&display=swap" },
  quicksand: { family: "Quicksand", url: "https://fonts.googleapis.com/css2?family=Quicksand:wght@100..900&display=swap" },
  mulish: { family: "Mulish", url: "https://fonts.googleapis.com/css2?family=Mulish:wght@100..900&display=swap" },
  heebo: { family: "Heebo", url: "https://fonts.googleapis.com/css2?family=Heebo:wght@100..900&display=swap" },
  oxygen: { family: "Oxygen", url: "https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" },
  karla: { family: "Karla", url: "https://fonts.googleapis.com/css2?family=Karla:wght@100..900&display=swap" },

  spaceGrotesk: { family: "Space Grotesk", url: "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@100..900&display=swap" },
  outfit: { family: "Outfit", url: "https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" },
  sora: { family: "Sora", url: "https://fonts.googleapis.com/css2?family=Sora:wght@100..900&display=swap" },
  plusJakartaSans: { family: "Plus Jakarta Sans", url: "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100..900&display=swap" },
  urbanist: { family: "Urbanist", url: "https://fonts.googleapis.com/css2?family=Urbanist:wght@100..900&display=swap" },
  lexend: { family: "Lexend", url: "https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" },
  figtree: { family: "Figtree", url: "https://fonts.googleapis.com/css2?family=Figtree:wght@100..900&display=swap" },
  overpass: { family: "Overpass", url: "https://fonts.googleapis.com/css2?family=Overpass:wght@100..900&display=swap" },
  cabin: { family: "Cabin", url: "https://fonts.googleapis.com/css2?family=Cabin:wght@100..900&display=swap" },
  assistant: { family: "Assistant", url: "https://fonts.googleapis.com/css2?family=Assistant:wght@100..900&display=swap" },

  playfairDisplay: { family: "Playfair Display", url: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@100..900&display=swap" },
  merriweather: { family: "Merriweather", url: "https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&display=swap" },
  libreBaskerville: { family: "Libre Baskerville", url: "https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap" },
  crimsonText: { family: "Crimson Text", url: "https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;600;700&display=swap" },
  lora: { family: "Lora", url: "https://fonts.googleapis.com/css2?family=Lora:wght@100..900&display=swap" },
  cormorant: { family: "Cormorant", url: "https://fonts.googleapis.com/css2?family=Cormorant:wght@100..900&display=swap" },
  alegreya: { family: "Alegreya", url: "https://fonts.googleapis.com/css2?family=Alegreya:wght@100..900&display=swap" },
  vollkorn: { family: "Vollkorn", url: "https://fonts.googleapis.com/css2?family=Vollkorn:wght@100..900&display=swap" },
  ptSerif: { family: "PT Serif", url: "https://fonts.googleapis.com/css2?family=PT+Serif:wght@400;700&display=swap" },
  spectralElite: { family: "Special Elite", url: "https://fonts.googleapis.com/css2?family=Special+Elite&display=swap" },

  jetBrainsMono: { family: "JetBrains Mono", url: "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@100..900&display=swap" },
  firaCode: { family: "Fira Code", url: "https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap" },
  sourceCodePro: { family: "Source Code Pro", url: "https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@200..900&display=swap" },
  inconsolata: { family: "Inconsolata", url: "https://fonts.googleapis.com/css2?family=Inconsolata:wght@200..900&display=swap" },
  ibmPlexMono: { family: "IBM Plex Mono", url: "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@100..700&display=swap" },
  spaceMono: { family: "Space Mono", url: "https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap" },
  ubuntuMono: { family: "Ubuntu Mono", url: "https://fonts.googleapis.com/css2?family=Ubuntu+Mono:wght@400;700&display=swap" },
  courierPrime: { family: "Courier Prime", url: "https://fonts.googleapis.com/css2?family=Courier+Prime:wght@400;700&display=swap" },
  anonymousPro: { family: "Anonymous Pro", url: "https://fonts.googleapis.com/css2?family=Anonymous+Pro:wght@400;700&display=swap" },
  victorMono: { family: "Victor Mono", url: "https://fonts.googleapis.com/css2?family=Victor+Mono:wght@100..700&display=swap" },

  // ─── Modern & Small ───────────────────────────────────────────────────────
  geist: { family: "Geist", url: "https://fonts.googleapis.com/css2?family=Geist:wght@100..900&display=swap" },
  interTight: { family: "Inter Tight", url: "https://fonts.googleapis.com/css2?family=Inter+Tight:wght@100..900&display=swap" },
  barlow: { family: "Barlow", url: "https://fonts.googleapis.com/css2?family=Barlow:wght@100..900&display=swap" },
  notoSans: { family: "Noto Sans", url: "https://fonts.googleapis.com/css2?family=Noto+Sans:wght@100..900&display=swap" },

  // ─── Elegant & Bold ───────────────────────────────────────────────────────
  bodoniModa: { family: "Bodoni Moda", url: "https://fonts.googleapis.com/css2?family=Bodoni+Moda:wght@400..900&display=swap" },
  fraunces: { family: "Fraunces", url: "https://fonts.googleapis.com/css2?family=Fraunces:wght@100..900&display=swap" },
  dmSerifDisplay: { family: "DM Serif Display", url: "https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap" },
  clashDisplay: { family: "Clash Display", url: "https://api.fontshare.com/v2/css?f[]=clash-display@400,500,600,700&display=swap" },

  // ─── Robotic / Techie ─────────────────────────────────────────────────────
  orbitron: { family: "Orbitron", url: "https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&display=swap" },
  exo2: { family: "Exo 2", url: "https://fonts.googleapis.com/css2?family=Exo+2:wght@100..900&display=swap" },
  rajdhani: { family: "Rajdhani", url: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" },
  saira: { family: "Saira", url: "https://fonts.googleapis.com/css2?family=Saira:wght@100..900&display=swap" },

  // ─── Apple-style ──────────────────────────────────────────────────────────
  nunitoSans: { family: "Nunito Sans", url: "https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200..900&display=swap" },
};